function  Run_Step03( BASEdir )
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Wrote by David André Barrière 09th September 2022
% This function permit to create and launch non linear normalization 
% (DARTEL), spatial smoothing and paired t-test comparison using SPM8 
% function.
%
% Usage : set BASEdir variable with your current working directory 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    % SPM Batch to load
T = load( 'processing_step03_MultiSubject.mat' ) ;


    % list of SPM function to run
TemplateJob = { [ BASEdir,...
                  '/processing_step03_Template.mat' ] } ;

    % Segmented Data Directory
DataDir = [ BASEdir,...
            '/02-LinearNormalisation' ] ;
          
mkdir ( [ BASEdir,...
          '/03-DiffeoMorphicNormalisation' ] ) ;

mkdir ( [ BASEdir,...
          '/04-StatisticalAnalysis' ] ) ;
      
mkdir ( [ BASEdir,...
          '/04-StatisticalAnalysis',...
          '/Data' ] ) ;

mkdir ( [ BASEdir,...
          '/04-StatisticalAnalysis',...
          '/Paired_t-test' ] ) ;

OutputDir_01 = { [ BASEdir,...
                   '/03-DiffeoMorphicNormalisation' ] } ;

OutputDir_02 = { [ BASEdir,...
                  '/04-StatisticalAnalysis',...
                  '/Data' ] } ;

OutputDir_03 = { [ BASEdir,...
                   '/04-StatisticalAnalysis',...
                   '/Paired_t-test' ] } ;

    % Segmented Data 
        %Grey Matter Data
GmData = dir( fullfile( [ DataDir,...
                          '/wc1rsub*_Normalized_N4_NLM.nii' ] ) ) ;

for i = 1 : 1 : 34
    GmDataList{i} = [DataDir,'/' GmData(i).name] ;
end

        %White Matter Data
WmData = dir( fullfile( [ DataDir,...
                          '/wc2rsub*_Normalized_N4_NLM.nii' ] ) ) ;
for i = 1 : 1 : 34
    WmDataList{i} = [DataDir,'/' WmData(i).name] ;
end

    % Image for brain masking
mask = { [ BASEdir,...
           '/00-DataSet',...
           '/Turone_Sheep_Brain_Template_And_Atlas',...
           '/brain_Templates',...
           '/mask_brain.nii,1' ] } ;
                
ReferenceNii = { [ BASEdir,...
                   '/04-StatisticalAnalysis',...
                   '/Data',...
                   '/swwc1rsub-01_IR_Sess_01_Normalized_N4_NLM.nii,1' ] } ;

    % Data for paired t-test comparison
Sub01 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-01_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-01_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub02 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-02_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-02_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub03 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-03_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-03_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub04 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-04_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-04_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub05 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-05_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-05_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub06 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-06_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-06_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub07 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-07_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-07_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub08 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-08_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-08_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub09 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-09_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-09_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub10 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-10_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-10_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub11 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-11_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-11_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub12 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-12_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-12_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub13 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-13_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-13_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub14 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-14_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-14_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub15 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-15_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-15_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub16 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-16_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-16_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

Sub17 = { [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-17_IR_Sess_01_Normalized_N4_NLM.nii,1' ],...
            [ BASEdir,...
            '/04-StatisticalAnalysis',...
            '/Data',...
            '/swwc1rsub-17_IR_Sess_02_Normalized_N4_NLM.nii,1' ] } ;

    % Create SPM Batch
T.matlabbatch{1}.cfg_basicio.runjobs.jobs = TemplateJob ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{1}.innifti = GmDataList ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{2}.innifti = WmDataList ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{3}.innifti = GmDataList ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{4}.indir = OutputDir_01 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{5}.indir = OutputDir_02 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{6}.innifti = ReferenceNii ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{7}.innifti = mask ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{8}.indir = OutputDir_03 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{9}.innifti = Sub01 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{10}.innifti = Sub02 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{11}.innifti = Sub03 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{12}.innifti = Sub04 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{13}.innifti = Sub05 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{14}.innifti = Sub06 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{15}.innifti = Sub07 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{16}.innifti = Sub08 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{17}.innifti = Sub09 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{18}.innifti = Sub10 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{19}.innifti = Sub11 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{20}.innifti = Sub12 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{21}.innifti = Sub13 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{22}.innifti = Sub14 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{23}.innifti = Sub15 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{24}.innifti = Sub16 ;
T.matlabbatch{1}.cfg_basicio.runjobs.inputs{1}{25}.innifti = Sub17 ;

    % Run SPM Batch
matlabbatch = T.matlabbatch ;
save(  'processing_step03_MultiSubject_Loaded', 'matlabbatch'  ) ;
spm_jobman('run',matlabbatch);  